auctions/urls.py
from django.urls import path

from auctions import views

urlpatterns = [
    path("", views.home, name="home"),
    path("listings/", views.all_auctions, name="listings"),
    path("listings/<slug:slug>/", views.category_view, name="category-filter"),
    path("add_to_watchlist/<str:item_id>/", views.add_to_watchlist, name="add-to-watchlist"),
    path("remove_from_watchlist/<str:item_id>/", views.remove_from_watchlist, name="remove-from-watchlist"),
    path("listings/item/<slug:slug>/", views.item_details, name="item-details"),
    path("watchlist/", views.watchlist_item, name="watchlist-items"),
    path("create_listing/", views.create_listing, name="create-listings"),
    path("close_auction/<slug:slug>", views.close_auction, name="close-auction"),
    path("closed_listings/", views.closed_listings, name="closed-listings"),
    path("closed_listings/<slug:slug>/", views.closed_category_view, name="closed-category-filter"),
    path("closed_listings/item/<slug:slug>/", views.closed_item_details, name="closed-item-details"),
    path("comment/<slug:item_slug>/", views.comment_form_in_item, name="comment"),
    path("auction/<slug:item_slug>/", views.auction_bid_form_in_item, name="auction_bid"),
    path("search/", views.search, name="search"),
    path("closed_search/", views.search, name="closed-search"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

commerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls")),
    path("users/", include("users.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from users import views

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register")
]

auctions/models.py
import uuid

from autoslug import AutoSlugField
# from cloudinary.models import CloudinaryField
from django.core.validators import MinValueValidator
from django.db import models

from users.models import User


class Category(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=255, null=True)
    slug = AutoSlugField(populate_from="name", always_update=True, unique=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = 'Categories'

    def __str__(self):
        return str(self.name)


class AuctionItem(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    name = models.CharField(max_length=255, null=True)
    slug = AutoSlugField(populate_from="name", always_update=True, unique=True)
    # image = CloudinaryField('items', null=True, blank=True)
    image = models.ImageField(default='default.jpg', blank=True, null=True)
    image_link = models.URLField(max_length=300, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, default=None, related_name="items")
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1)], null=True,
                                default=0)
    starting_bid = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1)], default=0,
                                       null=True)
    listed_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="item")
    winner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="items_won")
    closed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Auction Item"
        verbose_name_plural = "Auction Items"
        ordering = ["-created"]

    def __str__(self):
        return str(self.name)

    def image_url(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

    @property
    def auction_item_bidders(self):
        queryset = self.bids.all().values_list("bidder_id", flat=True)
        return queryset

    @property
    def commenters(self):
        queryset = self.comments.all().values_list("owner_id", flat=True)
        return queryset


class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, related_name="watchlists")
    item = models.ForeignKey(AuctionItem, on_delete=models.CASCADE, null=True)

    class Meta:
        # to make sure 2 exact objects don't exist
        constraints = [
            models.UniqueConstraint(fields=["user", "item"], name="unique_user_item_watchlist")
        ]

    def __str__(self):
        return f"{self.user} -- {self.item}"


class AuctionBid(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    item = models.ForeignKey(AuctionItem, related_name='bids', on_delete=models.CASCADE)
    bidder = models.ForeignKey(User, related_name='bidded_item', on_delete=models.CASCADE)
    bid = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(1)], default=0, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Auction Bid"
        verbose_name_plural = "Auction Bids"
        ordering = ["created"]

    def __str__(self):
        return f"{self.bidder} - {self.item} - {self.bid}"


class Comment(models.Model):
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments", null=True)
    item = models.ForeignKey(AuctionItem, related_name='comments', on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        # to make sure 2 exact objects don't exist
        constraints = [
            models.UniqueConstraint(fields=["owner", "item"], name="unique_user_item_comment")
        ]

    def __str__(self):
        return f"{self.owner} - {self.item}"

auctions/views.py
import random

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, reverse, get_object_or_404, redirect

from auctions.forms import AuctionForm, CommentForm, AuctionBidForm
from auctions.models import AuctionItem, Category, Watchlist, AuctionBid
from auctions.utils import watchlist_items_in_details, closed_items_in_details, paginate_items


def home(request):
    # this function selects and displays 6 random items on the main page
    featured_items = AuctionItem.objects.select_related('category').order_by("-id").all().exclude(closed=True)
    count = 6
    if featured_items.count() < 6:
        count = featured_items.count()
    featured_items = random.sample(list(featured_items), count)
    context = {"featured_items": featured_items}
    return render(request, "templates/index.html", context)


def all_auctions(request):
    # this function handles all categories and active listings and pagination
    categories = Category.objects.all()
    items = AuctionItem.objects.all().exclude(closed=True)
    custom_range, items = paginate_items(request, items, 9)
    context = {"categories": categories, "items": items, "custom_range": custom_range}
    return render(request, "auctions/all-auctions.html", context)


def category_view(request, slug):
    # this function returns item filtered by their category
    categories = Category.objects.all()
    try:
        category = categories.get(slug=slug)
    except Category.DoesNotExist:
        raise Http404()
    items = category.items.all()
    custom_range, items = paginate_items(request, items, 9)
    context = {"items": items, "category": category, "categories": categories, "custom_range": custom_range}
    return render(request, "auctions/auction-filter.html", context)


@login_required(login_url="login")
def item_details(request, slug):
    # handles the item details, auction and comment form including the logic
    item, watchlist_items = watchlist_items_in_details(request, slug)
    auction_bid_form = AuctionBidForm()
    all_comments = item.comments.all()
    comment_form = CommentForm()

    # if number of bids appearing in the template is more than 3, get the 3 latest bids
    previous_bids = AuctionBid.objects.filter(item=item).order_by("-created")
    if previous_bids.count() > 3:
        previous_bids = previous_bids[:3]

    context = {"item": item, "watchlist_items": watchlist_items, "auction_bid_form": auction_bid_form,
               "previous_bids": previous_bids, "comment_form": comment_form, "all_comments": all_comments}
    return render(request, "auctions/auction-detail.html", context)


@login_required(login_url="login")
def watchlist_item(request):
    # displays the watchlist items of each user and filter by search
    owner = request.user
    watchlist_items = Watchlist.objects.filter(user=owner)
    custom_range, watchlist_items = paginate_items(request, watchlist_items, 9)
    results = []
    if request.method == "GET":
        watchlist_search_query = request.GET.get("watchlist-search-query")
        if watchlist_search_query is not None:
            results = watchlist_items.filter(
                Q(item__name__icontains=watchlist_search_query) | Q(item__price__icontains=watchlist_search_query) |
                Q(item__listed_by__first_name__icontains=watchlist_search_query) |
                Q(item__listed_by__last_name__icontains=watchlist_search_query) |
                Q(item__description__icontains=watchlist_search_query))
    context = {"watchlist_items": watchlist_items, "owner": owner, "results": results,
               "watchlist_search_query": watchlist_search_query, "custom_range": custom_range}
    return render(request, "auctions/watchlist.html", context)


@login_required(login_url="login")
def add_to_watchlist(request, item_id):
    # adds a particular item to a user's watchlist
    item = get_object_or_404(AuctionItem, id=item_id, closed=False)
    Watchlist.objects.get_or_create(user=request.user, item=item)
    messages.info(request, "{} has been added to watchlist".format(item.name))
    return HttpResponseRedirect(reverse('watchlist-items'))


@login_required(login_url="login")
def remove_from_watchlist(request, item_id):
    # removes a particular item to a user's watchlist
    item = get_object_or_404(Watchlist, id=item_id)
    # if item belongs to the current authenticated user, remove it
    if item.user == request.user:
        item.delete()
        messages.info(request, "{} has been removed from watchlist".format(item.item.name))
    return HttpResponseRedirect(reverse('watchlist-items'))


@login_required(login_url="login")
def create_listing(request):
    # handles the creation of a new auction item by the user
    owner = request.user

    if request.method == "POST":
        form = AuctionForm(request.POST, request.FILES)
        if form.is_valid():
            auction_item = form.save(commit=False)
            auction_item.listed_by = owner
            auction_item.save()

            messages.success(request, "Item {} has been added successfully".format(auction_item.name))

            return HttpResponseRedirect(reverse('listings'))
        messages.error(request, "Error adding item")
        return render(request, "auctions/create-listing.html", {"form": form})
    else:
        form = AuctionForm()
        return render(request, "auctions/create-listing.html", {"form": form})


@login_required(login_url="login")
def close_auction(request, slug):
    # handles the closing of an auction
    item = get_object_or_404(AuctionItem, slug=slug, closed=False)
    # if bids exists for the item and the logged in user is the lister, auction can be closed
    if item.bids.exists() and item.listed_by == request.user:
        winner = item.bids.last().bidder
        last_bidder = f"{winner.first_name} {winner.last_name}"
        item.closed = True
        item.winner = winner
        messages.success(request, "You closed an auction on {} and {} won the auction".format(item.name, last_bidder))
        item.save()
    else:
        item.closed = True
        messages.success(request, "You closed an auction on {}".format(item.name))
        item.save()
    return HttpResponseRedirect(reverse("listings"))


@login_required(login_url="login")
def closed_listings(request):
    # displays all closed items
    categories = Category.objects.all()
    closed_items = AuctionItem.objects.filter(closed=True)
    custom_range, closed_items = paginate_items(request, closed_items, 9)
    results = []
    if request.method == "GET":
        closed_search_query = request.GET.get("closed-search-query")
        if closed_search_query is not None:
            results = AuctionItem.objects.filter(
                Q(name__icontains=closed_search_query) | Q(price__icontains=closed_search_query) |
                Q(listed_by__first_name__icontains=closed_search_query) |
                Q(listed_by__last_name__icontains=closed_search_query) |
                Q(description__icontains=closed_search_query), closed=True)
    context = {"closed_items": closed_items, "categories": categories, "closed_search_query": closed_search_query,
               "results": results, "custom_range": custom_range}
    return render(request, "auctions/closed-listings.html", context)


@login_required(login_url="login")
def closed_category_view(request, slug):
    # displays the closed items filtered by their category
    categories = Category.objects.all()
    try:
        category = categories.get(slug=slug)
    except Category.DoesNotExist:
        raise Http404()
    closed_items = category.items.filter(closed=True)
    custom_range, closed_items = paginate_items(request, closed_items, 9)
    context = {"closed_items": closed_items, "category": category, "categories": categories,
               "custom_range": custom_range}
    return render(request, "auctions/closed-auction-filter.html", context)


@login_required(login_url="login")
def closed_item_details(request, slug):
    # handles closed item details and comments
    item, other_closed_item = closed_items_in_details(slug)
    all_comments = item.comments.all()
    # if bids exist, the last bidder is the winner
    try:
        item_winner = item.bids.last().bidder
    except:
        item_winner = None
    item_bidders = item.auction_item_bidders
    # if number of bids appearing in the template is more than 3, get the 3 latest bids
    previous_bids = AuctionBid.objects.filter(item=item).order_by("-created")
    if previous_bids.count() > 3:
        previous_bids = previous_bids[:3]
    context = {"item": item, "other_closed_items": other_closed_item, "item_winner": item_winner,
               "previous_bids": previous_bids, "item_bidders": item_bidders, "all_comments": all_comments}
    return render(request, "auctions/closed-auction-detail.html", context)


# this function handles the auction form view
# passes the url of the view in the action of the form template
@login_required(login_url="login")
def auction_bid_form_in_item(request, item_slug):
    # handles the place bid form in the item
    try:
        item = AuctionItem.objects.get(slug=item_slug, closed=False)
    except AuctionItem.DoesNotExist:
        raise Http404()
    if request.user != item.listed_by and request.method == "POST" and "auction-btn" in request.POST:
        auction_bid_form = AuctionBidForm(request.POST)
        if auction_bid_form.is_valid():
            bid_price = auction_bid_form.save(commit=False)
            bid_price.bidder = request.user
            bid_price.item = item

            # checking if the bid price is less than the starting bid specified by the item owner
            if bid_price.bid <= item.starting_bid:
                messages.error(request, "Your bid is less than the starting price")
            else:

auctions/templates/auctions/all-auctions.html
{% extends 'templates/main.html' %}
{% load custom_tags %}
{% load static %}

{% block body %}
    <!-- Header Section -->
    <div class="container-fluid bg-danger py-5 text-white">
        <div class="row pt-5">
            <div class="col-12 col-lg-10 d-grid gap-3 d-md-flex justify-content-between align-items-center">
                <h1 class="display-5 fw-bold ms-0 ps-0 ms-md-5 ps-md-5 pt-3">Active Listings</h1>

                <!-- Search -->
                <div class="row pt-5">
                    <form class="form-inline" method="get" action="{% url 'search' %}">
                        <input class="form-control mr-sm-0" type="search" name="search-query" placeholder="Search"
                               aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" name="search-btn" type="submit">Search
                        </button>
                    </form>
                </div>

                <div class="">
                    <button class="btn btn-primary px-3 py-2" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                        Categories
                    </button>
                </div>


                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
                     aria-labelledby="offcanvasWithBothOptionsLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Backdrop </h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body text-secondary">
                        <h2 class="mb-3">Categories</h2>

                        <!-- on click of any child item, it would filter based on context -->
                        <div class="d-grid gap-1 text-center text-white categories">
                            <!-- All categories -->
                            {% for category in categories %}
                                <a class="my-2 mx-3 py-3 bg-secondary" data-bs-dismiss="offcanvas" aria-label="Close"
                                   onclick="window.location=`{% url 'category-filter' category.slug %}`">
                                    <h5>{{ category.name }}</h5></a>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Live Auction -->
    <div class="container-fluid">


        <div class="row mx-md-3 mb-5 p-md-3">
            <!-- Iterating over items to get each item -->

            <!-- Here ...Start -->
            {% for item in items %}
                <div class="col-12 col-md-6 col-lg-4 p-3 auction-card  text-center">
                    <div class=" p-3 auction border border-outline-1">
                        <a href="{% url 'item-details' item.slug %}">
                            <div class="auction-photo">
                                <img src="{{ item.image_url }}" alt="auction-1" class="img-fluid">
                                <p class="fw-bold auction-time text-danger bg-white m-0 p-3 mx-auto">{{ item.name }}</p>
                            </div>
                        </a>
                        <div class="auction-details">
                            <h3 class="text-start fs-4">{{ item.description|slice:"30" }}<span
                                    style="color: red;">...</span></h3>
                            <div class="auctioner my-3 d-flex justify-content-between">
                                <div class="user d-flex align-items-center">
                                    <img src="{% static 'assets/images/auction-authr1.png' %}" alt="auction author"
                                         class="img-fluid me-3">
                                    <p class="">
                                        By {{ item.listed_by.first_name.capitalize }} {{ item.listed_by.last_name.capitalize }}</p>
                                </div>

                                <h4 class="text-danger">${{ item.price }}</h4>
                            </div>
                            <div class="auction-action d-flex align-items-center justify-content-start">
                                <div class="cta text-start d-grid me-auto">
                                <!-- item watchers -->
                                {% if item.watchlist_set.count != 0 %}
                                    <p class="text-danger">{{ item.watchlist_set.count }} watching</p>
                                {% endif %}

                                    <!-- if item does not exist in watchlist, show add to watchlist button -->
                                    {% if not item|check_watchlist_item_existence:request %}
                                        <a href="{% url 'add-to-watchlist' item.id %}"
                                           class="btn btn-md btn-danger mb-3" id="liveToastBtn">Add to Watchlist</a>
                                    {% endif %}
                                </div>
                                <div class="action-btns justify-content-between ms-auto">
                                    <div class="dropdown">
                                        <button class="btn" type="button" id="dropdownMenuButton1"
                                                data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="fa fa-2x  fa-solid fa-ellipsis-v"></i>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            <li><a class="dropdown-item" href="#">Don't see this product</a></li>
                                            <li><a class="dropdown-item" href="#">Report Product</a></li>
                                            <li><a class="dropdown-item" href="#">Claim product rights</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <br>
                <h4 class="text-danger fw-bold">No Active Listings</h4>
                <br>
                <a href="{% url 'create-listings' %}">
                    <div class="text-center d-grid d-lg-flex justify-content-lg-between justify-content-center">
                        <input type="submit" class="btn btn-danger mb-3 px-3" value="Add item">
                    </div>
                </a>
                <!-- To Here ...Stop... then you can delete these from below... be sure to collapse the blocks to have a better view -->

            {% endfor %}

        </div>
    </div>

{#    Pagination#}
    {% include "templates/pagination.html" with queryset=items custom_range=custom_range %}

{% endblock body %}

auctions/templates/auctions/auction-filter.html
{% extends 'templates/main.html' %}
{% load static %}

{% block body %}
    <!-- Header Section -->
    <div class="container-fluid bg-danger py-5 text-white">
        <div class="row pt-5">
            <div class="col-12 col-lg-10 d-grid gap-3 d-md-flex justify-content-between align-items-center">
                <h1 class="display-5 fw-bold ms-0 ps-0 ms-md-5 ps-md-5 pt-3">{{ category.name }}</h1>

                <div class="">
                    <button class="btn btn-primary px-3 py-2" type="button" data-bs-toggle="offcanvas"
                            data-bs-target="#offcanvasWithBothOptions" aria-controls="offcanvasWithBothOptions">
                        Categories
                    </button>
                </div>


                <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="offcanvasWithBothOptions"
                     aria-labelledby="offcanvasWithBothOptionsLabel">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title" id="offcanvasWithBothOptionsLabel">Backdrop </h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body text-secondary">
                        <h2 class="mb-3">Categories</h2>

                        <!-- on click of any child item, it would filter based on context -->
                        <div class="d-grid gap-1 text-center text-white categories">
                            {% for category in categories %}
                                <a class="my-2 mx-3 py-3 bg-secondary" data-bs-dismiss="offcanvas" aria-label="Close"
                                   onclick="window.location=`{% url 'category-filter' category.slug %}`">
                                    <h5>{{ category.name }}</h5></a>
                            {% endfor %}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Live Auction -->
    <div class="container-fluid">
        <div class="row mx-md-3 mb-5 p-md-3">
            <!-- i think if you are gonna have multiple items, continuous html blocks would be unhealthy, so you can use whater=ver function you have under your sleeves to replicate one column from  -->
            <!-- Here ...Start -->
            {% for item in items %}
                <div class="col-12 col-md-6 col-lg-4 p-3 auction-card  text-center">
                    <div class=" p-3 auction border border-outline-1">
                        <a href="{% url 'item-details' item.slug %}">
                            <div class="auction-photo">
                                <img src="{{ item.image_url }}" alt="auction-1" class="img-fluid">
                                <p class="fw-bold auction-time text-danger bg-white m-0 p-3 mx-auto">{{ item.name }}</p>
                            </div>
                        </a>
                        <div class="auction-details">
                            <h3 class="text-start fs-4">{{ item.description|slice:"30" }}<span
                                    style="color: red;">...</span></h3>
                            <div class="auctioner my-3 d-flex justify-content-between">
                                <div class="user d-flex align-items-center">
                                    <img src="{% static 'assets/images/auction-authr1.png' %}" alt="auction author"
                                         class="img-fluid me-3">
                                    <p class="">
                                        By {{ item.listed_by.first_name.capitalize }} {{ item.listed_by.last_name.capitalize }}</p>
                                </div>

                                <h4 class="text-danger">${{ item.price }}</h4>
                            </div>
                            <div class="auction-action d-flex align-items-center justify-content-start">
                                <div class="cta text-start d-grid me-auto">
                                    <button class="btn btn-md btn-danger mb-3">Place a Bid</button>
                                    <a>
                                        <button class="btn btn-md btn-danger mb-3" id="liveToastBtn">
                                            Add to Watchlist
                                        </button>
                                    </a>
                                </div>
                                <div class="action-btns justify-content-between ms-auto">
                                    <div class="dropdown">
                                        <button class="btn" type="button" id="dropdownMenuButton1"
                                                data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="fa fa-2x  fa-solid fa-ellipsis-v"></i>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                            <li><a class="dropdown-item" href="#">Don't see this product</a></li>
                                            <li><a class="dropdown-item" href="#">Report Product</a></li>
                                            <li><a class="dropdown-item" href="#">Claim product rights</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% empty %}
                <br>
                <h4 class="text-info fw-bold">No item under this category</h4>

                <!-- To Here ...Stop... then you can delete these from below... be sure to collapse the blocks to have a better view -->

            {% endfor %}

        </div>
    </div>

    {#    Pagination#}
    {% include "templates/pagination.html" with queryset=items custom_range=custom_range %}


{% endblock body %}

auctions/templates/auctions/create-listing.html
{% extends 'templates/main.html' %}

{% block body %}
    <!-- Header Section -->
    <div class="container-fluid bg-danger py-5 text-white">
        <div class="row pt-5">
            <div class="col-12 col-lg-10">
                <h1 class="display-5 fw-bold ms-0 ps-0 ms-md-5 ps-md-5 pt-3">Create a Listing</h1>
            </div>
        </div>
    </div>
    <main>
        <div class="container">
            <form action="{% url 'create-listings' %}" id="createListing" class="w-100 row py-5" method="POST"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        <label for="auctionImage" class="form-label fs-4">{{ field.label }}</label>
                        {{ field }}
                    </div>
                {% endfor %}

                <div class="col-12 mt-5 text-center">
                    <button type="submit" class="btn btn-lg btn-success btn-primary">Create Listing</button>
                </div>


            </form>
        </div>
    </main>
{% endblock body %}